name: "Newman Tests"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run API Tests
        run: newman run "Tests Demo.postman_collection.json" -e "Tests_Demo.postman_environment.json" --disable-unicode --reporters cli,htmlextra,junit --env-var "apiKey=${{ secrets.APIKEY }}"
